# Generated by Django 4.2.6 on 2023-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcribeaudio',
            options={'ordering': ['-pk']},
        ),
    ]
