# Generated by Django 4.2.6 on 2023-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_transcribeaudio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribeaudio',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
