# Generated by Django 4.2.6 on 2023-10-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_transcribeaudio_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcribeaudio',
            options={'ordering': ['-updated_at', 'status']},
        ),
    ]
