# Generated by Django 5.1.2 on 2024-10-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_alter_transcribeaudio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribeaudio',
            name='status',
        ),
        migrations.AlterModelOptions(
            name='transcribeaudio',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='transcribeaudio',
            name='name',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
