# Generated by Django 5.1.2 on 2024-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_remove_transcribeaudio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribeaudio',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcribeaudio',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transcribeaudio',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcribeaudio',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
