# Generated by Django 5.1.2 on 2024-10-17 17:35

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_transcribeaudio_end_transcribeaudio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcribeaudio',
            name='name',
            field=models.CharField(blank=True, default=audio.models.generate_short_id, max_length=100, null=True, unique=True),
        ),
    ]
