# Generated by Django 5.1.2 on 2024-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_transcribeaudio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribeaudio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
