services:
  web:
    build: ./app
    # command: python manage.py runserver 0.0.0.0:8000
    command: uvicorn cf.asgi:application --port 8020 --host 0.0.0.0
    volumes:
      # - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

    env_file:
      - ./.env
    expose:
      - 8020
    restart: unless-stopped
  # db:
  #   image: postgres:17rc1-bookworm
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8020:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: